spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample?useSSL=false
    username: root
    password: passw0rd
    driverClassName: com.mysql.cj.jdbc.Driver

doma:
  dialect: mysql
  sql-file-repository: no_cache